### ISSUE TITLE
Form Sources - Problemi di salvataggio

### ISSUE THREAD

**Issue by ludovicagaleazzo** [villaitatti/VeNiss#110]
Quando salvo una source e passo a compilare la successiva, il nome dell'autore della seconda source automaticamente si aggiorna anche su quella precedente! Così se ricambio la prima, me lo ritrovo nella seconda...

**Comment by ludovicagaleazzo** [comment]
Gianmarco, ho riprovato a inserire l'autore nelle sources e ora, anche refreshando, compare questo codice invece che il nome dopo che si è salvato
<img width="882" alt="Screenshot 2023-10-19 at 15 30 18" src="https://github.com/villaitatti/VeNiss/assets/52323561/9592e0f0-6750-469f-87ea-3876d7154e35">

**Comment by ludovicagaleazzo** [comment]
Mi sono resa conto che non lo fa per tutti, solo per alcuni.. non so davvero spiegare il perchè..

**Comment by gspinaci** [comment]
Intendi che non lo fa per tutti gli autori? MI puoi dire quali autori hai provato ad inserire?
