### ISSUE TITLE
Events_Aggiungere campi

### ISSUE THREAD

**Issue by ludovicagaleazzo** [villaitatti/VeNiss#129]
Nel form degli events aggiungere i seguenti campi:
- ISLAND
- EVENT'S TYPOLOGY
- RELATED ELEMENTS

**Comment by gspinaci** [comment]
Aggiunta di ISLAND e EVENT'S TYPOLOGY completata nella pr #166.
l'aggiunta di RELATED ELEMENTS richiede una PR a parte
