### ISSUE TITLE
record senza titolo

### ISSUE THREAD

**Issue by SimoneFatuzzoVeNiss** [villaitatti/VeNiss#131]
Nelle Sources ci sono molti record a cui è sparito il titolo, dunque non sono cliccabili e modificabili
![Screenshot 2023-10-09 182740](https://github.com/villaitatti/VeNiss/assets/124375619/ba33a63c-5a52-44e3-a45b-0e7cb7eae61b)

**Comment by gspinaci** [comment]
Il problema riscontrato è il seguente: Dato che è possibile inserire un massimo di due Attributed Title in italiano e in inglese, nella query della piattaforma che va a predere i dati delle sources da visualizzare nella tabella è necessario specificare che la label da mostrare sia quella inglese (o italiana se vogliamo).

Ora, le sources il cui titolo non viene visualizzato sono tutte sources in cui non è stato specificata la lingua del titolo. Per ovviare a questo problema ho reso l'intera della tabella cliccabile per navigare fino alla pagina di modifica della source.

In questo caso anche le source visualizzate in foto sono cliccabili e modificabili.
<img width="1274" alt="image" src="https://github.com/villaitatti/VeNiss/assets/8267319/05b1fed7-bd09-4238-be35-6c731f65c1e1">
