### ISSUE TITLE
Form events – più tipologie di evento

### ISSUE THREAD

**Issue by ludovicagaleazzo** [villaitatti/VeNiss#193]
Sarebbe possibile permettere l'introduzione di più tipologie di evento?
<img width="1454" alt="Screenshot 2024-05-16 at 17 04 57" src="https://github.com/villaitatti/VeNiss/assets/52323561/0eec6c0b-9b18-428f-aa36-4fe700fa7425">

**Comment by gspinaci** [comment]
Modificato il knowledge pattern <https://veniss.net/container/fieldDefinitionContainer/event_typology>.
Da adesso non c'è limite Massimo al numero di tipologie che può avere un evento.

<img width="1743" alt="immagine" src="https://github.com/villaitatti/VeNiss/assets/8267319/5181ba46-83b1-4b43-bdd0-8898c68d1797">
