### ISSUE TITLE
Nome Frame in automatico

### ISSUE THREAD

**Issue by ludovicagaleazzo** [villaitatti/VeNiss#85]
Immagino che sia una cosa piuttosto complessa ma aiuterebbe veramente tanto se, quando si apre un nuovo frame specifico (es. voglio selezionare nel Form Source un archivio ma questo non c'è e devo aggiungerlo nelle Authorities>Archives) si aprisse un nuovo frame con il nome di quello a cui si riferisce, es. AUTHORITIES-ARCHIVES

**Comment by gspinaci** [comment]
Questa feature è presente nell'ultima versione di RS. Per poter integrare RS all'interno del nostro progetto, sarebbe opportuno integrare le modifiche necessarie per il funzionamento di VeNiss direttamente nel codice sorgente di RS.
